// Welcome to DAX query view! Learn more about DAX queries at https://aka.ms/dax-queries.
// Right-click on tables, columns, or measures in the data pane to access quick queries, or ask Copilot for help writing DAX.
EVALUATE
SUMMARIZECOLUMNS (
    DimDate[Year],
    DimGeography[Region],
    "Sales", SUM ( FactSales[SalesAmount] ),
    "Target", SUM ( FactSalesTarget[TargetAmount] )
)
ORDER BY DimDate[Year], DimGeography[Region]